services:
  crawler:
    image: crawler-dev
    build:
      context: .
      args:
        OTEL_JAVA_AGENT_VERSION: v2.21.0 # OpenTelemetry Java agent releases target specific OpenTelemetry SDK versions.
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./metrics/java-agent.properties:/opentelemetry/java-agent.properties:ro
    environment:
      DATABASE_HOST: postgres

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./scripts/abwcf-schema-postgres.sql:/docker-entrypoint-initdb.d/abwcf-schema-postgres.sql:ro
#      - ./data/postgres:/var/lib/postgresql/data
    shm_size: 256mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme

  prometheus:
    image: prom/prometheus:v3.7.3
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#      - ./data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-otlp-receiver"
      - "--enable-feature=created-timestamp-zero-ingestion"

  grafana:
    image: grafana/grafana:12.2.1
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./metrics/grafana:/etc/grafana/provisioning:ro
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin # According to the logs, this is deprecated ("auth.anonymous.org_role is deprecated, only viewer role is supported").
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: changeme
#      GF_FEATURE_TOGGLES_ENABLE: dashboardNewLayouts,kubernetesDashboards,dashboardScene # Required to access the new experimental dynamic dashboards.
