{
 "title": "Actor-Based Web Crawling Framework",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Active Instances",
   "type": "table",
   "description": "Does not include instances whose metrics are considered stale by Prometheus.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance, \"actor_system.address\") ({\"abwcf.actor_system.uptime_seconds\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance) ({\"abwcf.fetcher.fetched_pages_total\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance) ({\"abwcf.fetcher.received_bytes_total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Instances",
     "type": "table",
     "description": "Includes instances whose metrics are considered stale by Prometheus, but does not always show the latest values (reason unknown).",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "max by(instance, \"actor_system.address\") ({\"abwcf.actor_system.uptime_seconds\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(instance) ({\"abwcf.fetcher.fetched_pages_total\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(instance) ({\"abwcf.fetcher.received_bytes_total\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Sharded Entities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Host Managers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{\"abwcf.host_managers\", instance=~\"$instance\"}",
     "legendFormat": "{{actor_system.address}}"
    }
   ]
  },
  {
   "title": "Number of Host Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "{\"abwcf.host_queues\", instance=~\"$instance\"}",
     "legendFormat": "{{actor_system.address}}"
    }
   ]
  },
  {
   "title": "Number of Page Managers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "{\"abwcf.page_managers\", instance=~\"$instance\"}",
     "legendFormat": "{{actor_system.address}}"
    }
   ]
  },
  {
   "title": "Fetchers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetched Pages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "increase({\"abwcf.fetcher.fetched_pages_total\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{actor_system.address}}{{actor.path}}"
      }
     ]
    },
    {
     "title": "Fetched Pages (Total)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{\"abwcf.fetcher.fetched_pages_total\", instance=~\"$instance\"}",
       "legendFormat": "{{actor_system.address}}{{actor.path}}"
      }
     ]
    },
    {
     "title": "Received Response Body Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase({\"abwcf.fetcher.received_bytes_total\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{actor_system.address}}{{actor.path}}"
      }
     ]
    },
    {
     "title": "Received Response Body Bytes (Total)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{\"abwcf.fetcher.received_bytes_total\", instance=~\"$instance\"}",
       "legendFormat": "{{actor_system.address}}{{actor.path}}"
      }
     ]
    },
    {
     "title": "Responses by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by(\"http.response.status_code\") (increase({\"abwcf.fetcher.received_responses_total\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Responses by Status Code (Total)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(\"http.response.status_code\") ({\"abwcf.fetcher.received_responses_total\", instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Responses by Content Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "label_replace(sum by(\"http.response.header.content-type\") (increase({\"abwcf.fetcher.received_responses_total\", instance=~\"$instance\"}[$__rate_interval])), \"http.response.header.content-type\", \"$1\", \"http.response.header.content-type\", \"\\\\[\\\"(.+)\\\"\\\\]\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Responses by Content Type (Total)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(sum by(\"http.response.header.content-type\") ({\"abwcf.fetcher.received_responses_total\", instance=~\"$instance\"}), \"http.response.header.content-type\", \"$1\", \"http.response.header.content-type\", \"\\\\[\\\"(.+)\\\"\\\\]\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "increase({\"abwcf.fetcher.exceptions\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{exception}}"
      }
     ]
    }
   ]
  },
  {
   "title": "URL Normalizers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed URLs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "increase({\"abwcf.url_normalizer.processed_urls_total\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{actor_system.address}}{{actor.path}}"
      }
     ]
    },
    {
     "title": "Processed URLs (Total)",
     "type": "stat",
     "gridPos": { "h": 16, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "URLs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{\"abwcf.url_normalizer.processed_urls_total\", instance=~\"$instance\"}",
       "legendFormat": "{{actor_system.address}}{{actor.path}}"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "increase({\"abwcf.url_normalizer.exceptions_total\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{exception}}"
      }
     ]
    }
   ]
  }
 ]
}