{
 "title": "Crawl Database Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pages by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status, count(*)\r\nFROM pages\r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Crawl Depth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max(crawl_depth), avg(crawl_depth)\r\nFROM pages"
    }
   ]
  },
  {
   "title": "Crawl Delay",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min(crawl_delay), max(crawl_delay), avg(crawl_delay)\r\nFROM hosts"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count(*)\r\nFROM hosts" }
   ]
  }
 ]
}