{
 "title": "URL Normalizer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Processed URLs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase({\"abwcf.url_normalizer.processed_urls_total\"}[$__rate_interval])",
     "legendFormat": "{{actor_system.address}}{{actor.path}}"
    }
   ]
  },
  {
   "title": "Processed URLs (Total)",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "URLs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"abwcf.url_normalizer.processed_urls_total\"}",
     "legendFormat": "{{actor_system.address}}{{actor.path}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase({\"abwcf.url_normalizer.exceptions_total\"}[$__rate_interval])",
     "legendFormat": "{{actor_system.address}}{{actor.path}} {{exception}}"
    }
   ]
  }
 ]
}